### ISSUE TITLE
ToDriverValue should return plain value type for pointers to basic types

### ISSUE THREAD

**Issue by slinso** [aarondl/opt#7]
I used omit.Val[*uint] for handling NULL values just because I always used pointers for this stuff. But that resulted in errors like

> sql: converting argument $1 type: non-Value type *uint returned from Value

In my fork I added to value.go:ToDriverValue

```
	// check if val is a pointer
	if refVal.Kind() == reflect.Ptr {
		if refVal.IsNil() {
			return nil, nil
		}

		refVal = refVal.Elem()
	}
```

It made my code work again. What do you think about it?

**Comment by aarondl** [comment]
The goal of this library is to not use pointers for nullability because generics gave us a slightly better way.

This API makes it safer to access something that may be null because unless you only use `MustGet()` there are safer ways of unwrapping it like `Get()` etc.

Furthermore, there are painful amounts of heap allocations and escaping occurring when we are using `*uint` If I have a struct (which is likely a pointer for performance reasons), but have 10 fields that are all nullable integers, I've created 10 tiny allocations the GC needs to track, and a ton of indirection to be able to access the full data of the struct. It's not an efficient access pattern for computers, and it puts undue pressure on the GC.

To do what you are doing properly you should be using `omitnull` package, to have values that could both be omitted but also be null.

The reason I don't want to merge a simple fix like this is because it encourages us to do the wrong thing (keep pointers for nullability on trivially small or primitive types) which cause bugs, and proliferates bad memory layouts and access patterns. Thanks for opening the discussion!

**Comment by slinso** [comment]
Thank you for your feedback. I get your point regarding heap allocations and shooting yourself in the foot with pointers.
I do not use `MustGet()`, because I do not want have panics... Maybe it is a good time to overthink old habits and get rid of the panics based on using pointers as well...
